### PR TITLE
Accept names with colon for XML namespace

### LINKED ISSUE #13: Getting "not a valid name" for value
Sample code [here](https://github.com/pswaminathan/bazel-kt-databinding-crash/pull/3):

```
$ bazel build //...
DEBUG: Rule 'grab_bazel_common' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1639505949 -0500"
DEBUG: Repository grab_bazel_common instantiated at:
  /Users/p/Code/examples/bazel-kt-databinding-crash/WORKSPACE:43:15: in <toplevel>
Repository rule git_repository defined at:
  /private/var/tmp/_bazel_p/a48d838470da09ddcc3c8b96c3b3efad/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
INFO: Analyzed 8 targets (1 packages loaded, 28 targets configured).
INFO: Found 8 targets...
ERROR: /Users/p/Code/examples/bazel-kt-databinding-crash/BUILD:17:22: DatabindingStubs //:app_lib-stubs failed: (Exit 1): db-compiler-lite failed: error executing command bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/grab_bazel_common/tools/db-compiler-lite/db-compiler-lite --package com.example.databinding.lib --resource-files ... (remaining 7 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Exception in thread "main" java.lang.IllegalArgumentException: not a valid name: android:drawableTint
	at com.squareup.javapoet.Util.checkArgument(Util.java:53)
	at com.squareup.javapoet.FieldSpec.builder(FieldSpec.java:91)
	at com.grab.databinding.stub.rclass.generator.ResToRClassGeneratorImpl.generate(ResToRClassGenerator.kt:76)
	at com.grab.databinding.stub.BindingStubCommand.run(BindingStubCommand.kt:85)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:170)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:16)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:258)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:255)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:273)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:298)
	at com.grab.databinding.stub.MainKt.main(main.kt:20)
INFO: Elapsed time: 0.461s, Critical Path: 0.30s
INFO: 5 processes: 5 internal.
FAILED: Build did NOT complete successfully
```

This code successfully builds with Gradle.

If I'm reading https://github.com/square/javapoet/blob/master/src/main/java/com/squareup/javapoet/FieldSpec.java#L91 correctly, I think the issue here is that we expect this to be a valid name. But that isn't actually required: it is common to define attributes in Android's xmlns.

### PR DESCRIPTION
**Pull request by pswaminathan**
It is not uncommon to have attrs defined on a custom view that are in the Android XML NS, e.g.

```xml
<resources>
    <declare-styleable name="IconToggleButton">
        <attr name="android:drawableTint" format="reference" />
        <attr name="icon" format="reference" />
        <attr name="colorTheme" format="enum">
            <enum name="DEFAULT" value="0" />
            <enum name="DARK" value="1" />
            <enum name="CREAM" value="2" />
        </attr>
        <attr name="themeCream" format="boolean" />
        <attr name="themeDark" format="boolean" />
    </declare-styleable>
</resources>
```

`android:drawableTint` here lets users set familiar attributes on custom views.

In order to support this, Gradle converts it to, in R.txt:

```
int styleable IconToggleButton_android_drawableTint 5
```

This suggests that the right way to account for it is to replace invalid characters with an underscore. It is possible there are more than this that should be allowed, but colon at least is probably indicative of an XML namespace, so it should be valid.

Fixes #13

### CODE REVIEW

File: tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/rclass/generator/ResToRClassGenerator.kt [hunk 1]
```diff
@@ -73,7 +73,7 @@ class ResToRClassGeneratorImpl constructor(
                         .toTypedArray()
 
                     fields.add(
-                        FieldSpec.builder(type, it.name)
+                        FieldSpec.builder(type, it.name.replace(":", "_"))
```
Comment (arunkumar9t2) [inline tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/rclass/generator/ResToRClassGenerator.kt:76]: Could you please move this logic to https://github.com/grab/grab-bazel-common/blob/240a1c393180c5121032e82e4603a124544c241b/tools/db-compiler-lite/src/main/java/com/grab/databinding/stub/rclass/parser/ResToRParser.kt#L223? I think that is where the `:` is getting added. Would prefer to have less processing done on generator class and fix things on the parser side.

**Comment by arunkumar9t2** [comment]
Thank you!
